rails/myrail1/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :articles
  get 'say/hello'
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

rails/myrail1/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails/myrail1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

rails/myrail1/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
  end
  def create 
    render plain : params[:article].inspect
  end
end

rails/myrail1/app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
    @time= Time.now
  end
end

rails/myrail1/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

rails/myrail1/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/myrail1/app/helpers/articles_helper.rb
module ArticlesHelper
end

rails/myrail1/app/helpers/say_helper.rb
module SayHelper
end

rails/myrail1/app/helpers/welcome_helper.rb
module WelcomeHelper
end

rails/myrail1/app/views/articles/new.html.erb
<h1>New Article</h1>

<%= form_with scope: :article, url: articles_path, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

rails/myrail1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myrail1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

rails/myrail1/app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>