rails/myrail2/config/routes.rb
Rails.application.routes.draw do
  resources :topics do
    member do
        post 'upvote'
    end
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

rails/myrail2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails/myrail2/app/models/topic.rb
class Topic < ApplicationRecord
    has_many :votes, dependent: :destroy
end

rails/myrail2/app/models/vote.rb
class Vote < ApplicationRecord
    belongs_to :topic
end

rails/myrail2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

rails/myrail2/app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def upvote
    @topic = Topic.find(params[:id])
    @topic.votes.create
    redirect_to(topics_path)
  end
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topics_path, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to topics_path, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:title, :descroption)
    end
end

rails/myrail2/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/myrail2/app/helpers/topics_helper.rb
module TopicsHelper
end

rails/myrail2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myrail2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

rails/myrail2/app/views/topics/_form.html.erb
<%= form_with(model: topic, local: true) do |form| %>
  <% if topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :topic_title %>
  </div>

  <div class="field">
    <%= form.label :descroption %>
    <%= form.text_area :descroption, id: :topic_descroption %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

rails/myrail2/app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

rails/myrail2/app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Topics</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Descroption</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.title %></td>
        <td><%= topic.descroption %></td>
        <td><%= topic.votes.count%></td>
        <td><%= button_to '投我投我',upvote_topic_path(topic),method: :post%></td>
        <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
        <td><%= link_to 'Delete', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topic', new_topic_path %>

rails/myrail2/app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Back', topics_path %>

rails/myrail2/app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @topic.title %>
</p>

<p>
  <strong>Descroption:</strong>
  <%= @topic.descroption %>
</p>

<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>